import express from "express";
import cors from "cors";
import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// Health check
app.get("/", (_req, res) => {
  res.json({ message: "Vino VIN Proxy is live ✅" });
});

// VIN lookup (mock)
app.post("/lookup", (req, res) => {
  const { vin } = req.body;
  if (!vin) return res.status(400).json({ error: "VIN missing" });
  res.json({ vin, result: "VIN lookup mock successful 🚗" });
});

// PDF Report generator
app.post("/report", async (req, res) => {
  const { vin, data } = req.body;
  if (!vin || !data)
    return res.status(400).json({ error: "VIN or data missing" });

  try {
    const doc = new PDFDocument();
    const filePath = path.join("/tmp", `${vin}.pdf`);
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc.fontSize(20).text("Vino Auto BenchLab Report", { align: "center" });
    doc.moveDown();
    doc.fontSize(14).text(`VIN: ${vin}`);
    doc.moveDown();
    doc.text(`Report Details:\n\n${data}`, { align: "left" });
    doc.moveDown();
    doc.fontSize(10).text("Generated by Vino Auto AI Diagnostics © Control.INC®", {
      align: "center",
    });
    doc.end();

    stream.on("finish", () => {
      res.download(filePath, `${vin}.pdf`);
    });
  } catch (err) {
    console.error("PDF generation error:", err);
    res.status(500).json({ error: "Failed to generate PDF report" });
  }
});

// Start server
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});